[{
	"vItemNumber": "113RW",
	"vLocation": "400",
	"vDescription": "Her hands are half of her expression, so she must always wear the most fab rings! This display holds 12 rings total and she can simply slide them off the display and try them on to see which style she wants to go with. They are all so gorg, we know she will want to purchase them all!",
	"vShortDesc": "White Leatherette Ring Display",
	"vLook": "Display",
	"vGenColor": "White",
	"vGenMaterial": "Leatherette",
	"vGenItemType": "Displays",
	"vMetalColor": "",
	"vSizeType": "",
	"vMetalType": "",
	"vKeywords": "Display,",
	"vOnSale": "N",
	"vFeaturedItem": "Y",
	"vSorting": 811,
	"vAggregation": null,
	"vMaterialDesc": "White leatherette material",
	"vFeatureDesc": "Display holds 12 rings | Style # 113RW",
	"vDetailDesc": "8\"x 3.75\"x 2.5\"| Designed in the USA",
	"itemprice_1": 15,
	"itemprice_2": 0,
	"quantityonhand": 32,
	"imagefilename": "https://www.cosmostylejewelry.com/CosmoImg/113RW.JPG, https://www.cosmostylejewelry.com/CosmoImg/113RW-2.JPG, https://www.cosmostylejewelry.com/CosmoImg/113RW-3.JPG, https://www.cosmostylejewelry.com/CosmoImg/113RW-4.JPG, https://www.cosmostylejewelry.com/CosmoImg/113RW-5.JPG"
}, {
	"vItemNumber": "C19394",
	"vLocation": "400",
	"vDescription": "She appreciates the stylish simplicity of adding a couple of her favorite bangles or cuffs to her #ootd. She loves to mix ‘n match them and stack them as the mood strikes, so this plush velveteen pillow is just the accessory you need to showcase how she can create the perfect bracelet stack for everything from a glam night out to weekend brunch with her girls. Perfect for The Grunge Glam Bracelet Stack or to displays about six of her other favorite CosmoStyle cuffs or bangles, glam bracelets will totally be her new go-to piece!",
	"vShortDesc": "White Display Pillow",
	"vLook": "Display",
	"vGenColor": "White",
	"vGenMaterial": "PU",
	"vGenItemType": "Displays",
	"vMetalColor": "",
	"vSizeType": "",
	"vMetalType": "",
	"vKeywords": "Display,",
	"vOnSale": "N",
	"vFeaturedItem": "Y",
	"vSorting": 811,
	"vAggregation": null,
	"vMaterialDesc": "White faux leather",
	"vFeatureDesc": "Long pillow for bracelet display | Style # C19394",
	"vDetailDesc": "7.75\"x2.65\"x2\"| Designed in the USA",
	"itemprice_1": 3,
	"itemprice_2": 0,
	"quantityonhand": 197,
	"imagefilename": "https://www.cosmostylejewelry.com/CosmoImg/C19394.JPG, https://www.cosmostylejewelry.com/CosmoImg/C19394-2.JPG, https://www.cosmostylejewelry.com/CosmoImg/C19394-3.JPG, https://www.cosmostylejewelry.com/CosmoImg/C19394-4.JPG, https://www.cosmostylejewelry.com/CosmoImg/C19394-5.JPG"
}, {
	"vItemNumber": "CD00PW",
	"vLocation": "400",
	"vDescription": "Stepping it up with our displays… pun intended! Choose the small or large display to show off your carded jewelry pieces. She and her bestie can shop together and if they fall in love with the same piece -- not to worry! Each step offers two slits to store an additional piece rather than adding it to your back stock inventory.",
	"vShortDesc": "The Large Slotted Step Display",
	"vLook": "Display",
	"vGenColor": "White",
	"vGenMaterial": "Acrylic",
	"vGenItemType": "Displays",
	"vMetalColor": "",
	"vSizeType": null,
	"vMetalType": "",
	"vKeywords": "",
	"vOnSale": "N",
	"vFeaturedItem": "N",
	"vSorting": 800,
	"vAggregation": null,
	"vMaterialDesc": "White acrylic material",
	"vFeatureDesc": "2 slots per step, 4 steps | Style # CD00PW",
	"vDetailDesc": "13.5x8x6\"| Designed in the USA",
	"itemprice_1": 35,
	"itemprice_2": 0,
	"quantityonhand": 393,
	"imagefilename": "https://www.cosmostylejewelry.com/CosmoImg/CD00PW.JPG, https://www.cosmostylejewelry.com/CosmoImg/CD00PW-2.JPG, https://www.cosmostylejewelry.com/CosmoImg/CD00PW-3.JPG, https://www.cosmostylejewelry.com/CosmoImg/CD00PW-4.JPG, https://www.cosmostylejewelry.com/CosmoImg/CD00PW-5.JPG"
}, {
	"vItemNumber": "CD113EW",
	"vLocation": "400",
	"vDescription": "Stepping it up with our displays… pun intended! Choose the small or large display to show off your carded jewelry pieces. She and her bestie can shop together and if they fall in love with the same piece -- not to worry! Each step offers two slits to store an additional piece rather than adding it to your back stock inventory.",
	"vShortDesc": "The Small Slotted Step Display",
	"vLook": "Display",
	"vGenColor": "White",
	"vGenMaterial": "Acrylic",
	"vGenItemType": "Displays",
	"vMetalColor": "",
	"vSizeType": null,
	"vMetalType": "",
	"vKeywords": "",
	"vOnSale": "N",
	"vFeaturedItem": "N",
	"vSorting": 800,
	"vAggregation": null,
	"vMaterialDesc": "White acrylic material",
	"vFeatureDesc": "2 slots per step, 3 steps | Style # CD113EW",
	"vDetailDesc": "13.5x6x3\"| Designed in the USA",
	"itemprice_1": 30,
	"itemprice_2": 0,
	"quantityonhand": 457,
	"imagefilename": "https://www.cosmostylejewelry.com/CosmoImg/CD113EW.JPG, https://www.cosmostylejewelry.com/CosmoImg/CD113EW-2.JPG, https://www.cosmostylejewelry.com/CosmoImg/CD113EW-3.JPG, https://www.cosmostylejewelry.com/CosmoImg/CD113EW-4.JPG, https://www.cosmostylejewelry.com/CosmoImg/CD113EW-5.JPG"
}, {
	"vItemNumber": "NF150L",
	"vLocation": "400",
	"vDescription": "",
	"vShortDesc": "The CosmoStyle Neckform - Large",
	"vLook": "Display",
	"vGenColor": "White",
	"vGenMaterial": "Acrylic",
	"vGenItemType": "Displays",
	"vMetalColor": "",
	"vSizeType": null,
	"vMetalType": "",
	"vKeywords": "",
	"vOnSale": "N",
	"vFeaturedItem": "N",
	"vSorting": 810,
	"vAggregation": null,
	"vMaterialDesc": "White acrylic material",
	"vFeatureDesc": "Style # NF150L",
	"vDetailDesc": "8.7x7.5x18.9\"| Designed in the USA",
	"itemprice_1": 30,
	"itemprice_2": 0,
	"quantityonhand": 184,
	"imagefilename": "https://www.cosmostylejewelry.com/CosmoImg/NF150L.JPG, https://www.cosmostylejewelry.com/CosmoImg/NF150L-2.JPG, https://www.cosmostylejewelry.com/CosmoImg/NF150L-3.JPG, https://www.cosmostylejewelry.com/CosmoImg/NF150L-4.JPG, https://www.cosmostylejewelry.com/CosmoImg/NF150L-5.JPG"
}, {
	"vItemNumber": "NF150S",
	"vLocation": "400",
	"vDescription": "",
	"vShortDesc": "The CosmoStyle Neckform - Small",
	"vLook": "Display",
	"vGenColor": "White",
	"vGenMaterial": "Acrylic",
	"vGenItemType": "Displays",
	"vMetalColor": "",
	"vSizeType": null,
	"vMetalType": "",
	"vKeywords": "",
	"vOnSale": "N",
	"vFeaturedItem": "N",
	"vSorting": 810,
	"vAggregation": null,
	"vMaterialDesc": "White acrylic material",
	"vFeatureDesc": "Style # NF150S",
	"vDetailDesc": "3.7x6.9x11.8\"| Designed in the USA",
	"itemprice_1": 20,
	"itemprice_2": 0,
	"quantityonhand": 160,
	"imagefilename": "https://www.cosmostylejewelry.com/CosmoImg/NF150S.JPG, https://www.cosmostylejewelry.com/CosmoImg/NF150S-2.JPG, https://www.cosmostylejewelry.com/CosmoImg/NF150S-3.JPG, https://www.cosmostylejewelry.com/CosmoImg/NF150S-4.JPG, https://www.cosmostylejewelry.com/CosmoImg/NF150S-5.JPG"
}, {
	"vItemNumber": "T113NW",
	"vLocation": "400",
	"vDescription": "Calling all accessory lovers! It's time to get excited. Whether she is shopping The Midnight Statement or The Posh Pearl, this display can be customized to the product you are offering her. Earrings, necklaces and bracelets that are on cards rest in the slotted steps of this display and loose necklaces and bracelets slide on the adjustable T-bar. To adjust the pole height, simply loosen the knob and change the height. She can't wait to see the killer collection you are offering her!",
	"vShortDesc": "The Slotted Adjustable T-Bar Display",
	"vLook": "Display",
	"vGenColor": "White",
	"vGenMaterial": "Metal/Leatherette/Acrylic",
	"vGenItemType": "Displays",
	"vMetalColor": "",
	"vSizeType": null,
	"vMetalType": "",
	"vKeywords": "",
	"vOnSale": "N",
	"vFeaturedItem": "N",
	"vSorting": 805,
	"vAggregation": null,
	"vMaterialDesc": "White acrylic base with adjustable metal poles and leatherette t-bar",
	"vFeatureDesc": "Adjustable t-bar | 3 steps, 2 slots on each step for carded items | Style # T113NW",
	"vDetailDesc": "Base: 13.5x7.3\"| Bar adjusts from 10.5\"to 18\"| Designed in the USA",
	"itemprice_1": 35,
	"itemprice_2": 0,
	"quantityonhand": 432,
	"imagefilename": "https://www.cosmostylejewelry.com/CosmoImg/T113NW.JPG, https://www.cosmostylejewelry.com/CosmoImg/T113NW-2.JPG, https://www.cosmostylejewelry.com/CosmoImg/T113NW-3.JPG, https://www.cosmostylejewelry.com/CosmoImg/T113NW-4.JPG, https://www.cosmostylejewelry.com/CosmoImg/T113NW-5.JPG"
}, {
	"vItemNumber": "TB113W",
	"vLocation": "400",
	"vDescription": "Customize and obsessorize! She loves necklaces of all lengths and is a bracelet fanatic, so of course we’re offering you a display that is versatile; this is something to get excited about! Whether you have The Chloe program or The Fashion First, this display can be altered to your product type. Simply loosen the knob on the pole(s) and adjust the height! Utilize the slit to show off your earrings or signage.",
	"vShortDesc": "The Slotted Adjustable Double T-Bar Display",
	"vLook": "Display",
	"vGenColor": "White",
	"vGenMaterial": "Metal/Leatherette",
	"vGenItemType": "Displays",
	"vMetalColor": "",
	"vSizeType": null,
	"vMetalType": "",
	"vKeywords": "",
	"vOnSale": "N",
	"vFeaturedItem": "N",
	"vSorting": 805,
	"vAggregation": null,
	"vMaterialDesc": "White acrylic base with adjustable metal poles and leatherette t-bars",
	"vFeatureDesc": "Adjustable t-bars | 2 slots in front for carded items | Style # TB113W",
	"vDetailDesc": "Base: 7.5x6\"| Front bar adjusts from 6.5\"to 10\"| Back bar adjusts from 10.5\"to 18\"| Designed in the USA",
	"itemprice_1": 30,
	"itemprice_2": 0,
	"quantityonhand": 399,
	"imagefilename": "https://www.cosmostylejewelry.com/CosmoImg/TB113W.JPG, https://www.cosmostylejewelry.com/CosmoImg/TB113W-2.JPG, https://www.cosmostylejewelry.com/CosmoImg/TB113W-3.JPG, https://www.cosmostylejewelry.com/CosmoImg/TB113W-4.JPG, https://www.cosmostylejewelry.com/CosmoImg/TB113W-5.JPG"
}, {
	"vItemNumber": "C190810101",
	"vLocation": "400",
	"vDescription": "Be starry-eyed and gleefully glam in this dainty take on grunge style! This hand bracelet is delicate in stature and lightweight in size but is not short on style factor! A great everyday piece for wearing from class or work to weekend fun, and everything in between.",
	"vShortDesc": "Seeing Stars Dainty Hand Bracelet",
	"vLook": "Grunge Glam",
	"vGenColor": "Gold",
	"vGenMaterial": "Metal",
	"vGenItemType": "Bracelets",
	"vMetalColor": "Gold",
	"vSizeType": "",
	"vMetalType": "Brass",
	"vKeywords": "Bracelet,",
	"vOnSale": "N",
	"vFeaturedItem": "Y",
	"vSorting": 318,
	"vAggregation": null,
	"vMaterialDesc": "Oxidized gold tone plating over brass",
	"vFeatureDesc": "Lobster claw closure | Style # C19081",
	"vDetailDesc": "7\"length | 1.5\"extender chain | Designed in the USA",
	"itemprice_1": 12,
	"itemprice_2": 24.99,
	"quantityonhand": 499,
	"imagefilename": "https://www.cosmostylejewelry.com/CosmoImg/C190810101.JPG, https://www.cosmostylejewelry.com/CosmoImg/C190810101-2.JPG, https://www.cosmostylejewelry.com/CosmoImg/C190810101-3.JPG, https://www.cosmostylejewelry.com/CosmoImg/C190810101-4.JPG, https://www.cosmostylejewelry.com/CosmoImg/C190810101-5.JPG"
}, {
	"vItemNumber": "C190930202",
	"vLocation": "400",
	"vDescription": "Be gleefully glam in this dainty take on grunge style! This hand bracelet is delicate in stature and lightweight in size, but is not short on style factor! A great everyday piece for wearing from class or work to weekend fun, and everything in between.",
	"vShortDesc": "What a Stud Dainty Hand Bracelet",
	"vLook": "Grunge Glam",
	"vGenColor": "Silver",
	"vGenMaterial": "Metal",
	"vGenItemType": "Bracelets",
	"vMetalColor": "Silver",
	"vSizeType": "",
	"vMetalType": "Brass",
	"vKeywords": "Bracelets",
	"vOnSale": "N",
	"vFeaturedItem": "Y",
	"vSorting": 320,
	"vAggregation": null,
	"vMaterialDesc": "Oxidized silver tone plating over brass",
	"vFeatureDesc": "Lobster claw closure | Style # C19093",
	"vDetailDesc": "7\"length | 1.5\"extender chain | Designed in the USA",
	"itemprice_1": 12,
	"itemprice_2": 24.99,
	"quantityonhand": 502,
	"imagefilename": "https://www.cosmostylejewelry.com/CosmoImg/C190930202.JPG, https://www.cosmostylejewelry.com/CosmoImg/C190930202-2.JPG, https://www.cosmostylejewelry.com/CosmoImg/C190930202-3.JPG, https://www.cosmostylejewelry.com/CosmoImg/C190930202-4.JPG, https://www.cosmostylejewelry.com/CosmoImg/C190930202-5.JPG"
}, {
	"vItemNumber": "C180990402",
	"vLocation": "400",
	"vDescription": "Wear cut off denim shorts and a slouchy tee with mix-matched rings, or stack them all for a to-die-for look! These pieces all have the natural elements and you'll love the versatility The Wanderlust Ring Set offers.",
	"vShortDesc": "The Wanderlust Ring Set",
	"vLook": "Boho Traveler Cali",
	"vGenColor": "Multi",
	"vGenMaterial": "Metal/Stone/Glass",
	"vGenItemType": "Rings",
	"vMetalColor": "Bronze/Silver",
	"vSizeType": null,
	"vMetalType": "Brass",
	"vKeywords": "Gemstone, stone, mixed metal, red agate, synthetic, turquoise, howlite",
	"vOnSale": "N",
	"vFeaturedItem": "N",
	"vSorting": 540,
	"vAggregation": null,
	"vMaterialDesc": "Bronze and silver tone plating over brass with red agate and turquoise howlite",
	"vFeatureDesc": "Adjustable | Style # C18099",
	"vDetailDesc": "Designed in the USA",
	"itemprice_1": 16,
	"itemprice_2": 32.99,
	"quantityonhand": 707,
	"imagefilename": "https://www.cosmostylejewelry.com/CosmoImg/C180990402.JPG, https://www.cosmostylejewelry.com/CosmoImg/C180990402-2.JPG, https://www.cosmostylejewelry.com/CosmoImg/C180990402-3.JPG, https://www.cosmostylejewelry.com/CosmoImg/C180990402-4.JPG, https://www.cosmostylejewelry.com/CosmoImg/C180990402-5.JPG"
}, {
	"vItemNumber": "C181010402",
	"vLocation": "400",
	"vDescription": "This stud pack offers you natural elements and versatility, what more can you ask for? You'll definitely want to be wearing a top knot so you can show off your Wanderlust Stud Earrings!",
	"vShortDesc": "The Wanderlust Stud Earring Pack",
	"vLook": "Boho Traveler Cali",
	"vGenColor": "Multi",
	"vGenMaterial": "Metal/Stone/Glass",
	"vGenItemType": "Earrings",
	"vMetalColor": "Bronze/Silver",
	"vSizeType": null,
	"vMetalType": "Surgical Steel",
	"vKeywords": "Gemstone, stone, mixed metal, red agate, synthetic, turquoise, howlite",
	"vOnSale": "N",
	"vFeaturedItem": "N",
	"vSorting": 535,
	"vAggregation": null,
	"vMaterialDesc": "Bronze and silver tone plating over surgical steel with red agate and turquoise howlite",
	"vFeatureDesc": "Surgical steel posts | Style # C18101",
	"vDetailDesc": "Designed in the USA",
	"itemprice_1": 16,
	"itemprice_2": 32.99,
	"quantityonhand": 709,
	"imagefilename": "https://www.cosmostylejewelry.com/CosmoImg/C181010402.JPG, https://www.cosmostylejewelry.com/CosmoImg/C181010402-2.JPG, https://www.cosmostylejewelry.com/CosmoImg/C181010402-3.JPG, https://www.cosmostylejewelry.com/CosmoImg/C181010402-4.JPG, https://www.cosmostylejewelry.com/CosmoImg/C181010402-5.JPG"
}, {
	"vItemNumber": "C180940109",
	"vLocation": "400",
	"vDescription": "This Diffuser Necklace is an essential piece for your lifestyle, especially since you're obsessed with looking good and feeling even better! When heading to yoga, apply a calming oil to your diffuser pad and place it in your necklace, when heading for a coffee date, use your favorite energy boosting oil.",
	"vShortDesc": "The Karma Hamsa Diffuser Necklace",
	"vLook": "Zen",
	"vGenColor": "Gold",
	"vGenMaterial": "Metal/Glass",
	"vGenItemType": "Necklaces",
	"vMetalColor": "Gold",
	"vSizeType": null,
	"vMetalType": "Brass",
	"vKeywords": "Pavé, crystal, CZ, cubiic zirconia, 14K, gold, plated, essential oil, felt",
	"vOnSale": "N",
	"vFeaturedItem": "N",
	"vSorting": 425,
	"vAggregation": null,
	"vMaterialDesc": "14k gold plated over brass with glass crystal accents",
	"vFeatureDesc": "Lobster claw closure | Style # C18094",
	"vDetailDesc": "20\"length | 3\"extender chain | Designed in the USA",
	"itemprice_1": 17.5,
	"itemprice_2": 34.99,
	"quantityonhand": 890,
	"imagefilename": "https://www.cosmostylejewelry.com/CosmoImg/C180940109.JPG, https://www.cosmostylejewelry.com/CosmoImg/C180940109-2.JPG, https://www.cosmostylejewelry.com/CosmoImg/C180940109-3.JPG, https://www.cosmostylejewelry.com/CosmoImg/C180940109-4.JPG, https://www.cosmostylejewelry.com/CosmoImg/C180940109-5.JPG"
}, {
	"vItemNumber": "C180950509",
	"vLocation": "400",
	"vDescription": "This Diffuser Necklace is an essential piece for your lifestyle, especially since you're obsessed with looking good and feeling even better! When heading to yoga, apply a calming oil to your diffuser pad and place it in your necklace, when heading for a coffee date, use your favorite energy boosting oil.",
	"vShortDesc": "The Karma Lotus Diffuser Necklace",
	"vLook": "Zen",
	"vGenColor": "Rose Gold",
	"vGenMaterial": "Metal/Glass",
	"vGenItemType": "Necklaces",
	"vMetalColor": "Rose Gold",
	"vSizeType": null,
	"vMetalType": "Brass",
	"vKeywords": "Pavé, crystal, CZ, cubiic zirconia, 14K, rose gold, plated, essential oil, felt",
	"vOnSale": "N",
	"vFeaturedItem": "N",
	"vSorting": 425,
	"vAggregation": null,
	"vMaterialDesc": "14k rose gold plated over brass with glass crystal accents",
	"vFeatureDesc": "Lobster claw closure | Style # C18095",
	"vDetailDesc": "20\"length | 3\"extender chain | Designed in the USA",
	"itemprice_1": 17.5,
	"itemprice_2": 34.99,
	"quantityonhand": 888,
	"imagefilename": "https://www.cosmostylejewelry.com/CosmoImg/C180950509.JPG, https://www.cosmostylejewelry.com/CosmoImg/C180950509-2.JPG, https://www.cosmostylejewelry.com/CosmoImg/C180950509-3.JPG, https://www.cosmostylejewelry.com/CosmoImg/C180950509-4.JPG, https://www.cosmostylejewelry.com/CosmoImg/C180950509-5.JPG"
}, {
	"vItemNumber": "C180960209",
	"vLocation": "400",
	"vDescription": "This Diffuser Necklace is an essential piece for your lifestyle, especially since you're obsessed with looking good and feeling even better! When heading to yoga, apply a calming oil to your diffuser pad and place it in your necklace, when heading for a coffee date, use your favorite energy boosting oil.",
	"vShortDesc": "The Karma Triangle Diffuser Necklace",
	"vLook": "Zen",
	"vGenColor": "Silver",
	"vGenMaterial": "Metal/Glass",
	"vGenItemType": "Necklaces",
	"vMetalColor": "Silver",
	"vSizeType": null,
	"vMetalType": "Brass",
	"vKeywords": "Pavé, crystal, CZ, cubiic zirconia, rhodium, plated, essential oil, felt",
	"vOnSale": "N",
	"vFeaturedItem": "N",
	"vSorting": 425,
	"vAggregation": null,
	"vMaterialDesc": "Rhodium plated over brass with glass crystal accents",
	"vFeatureDesc": "Lobster claw closure | Style # C18096",
	"vDetailDesc": "20\"length | 3\"extender chain | Designed in the USA",
	"itemprice_1": 17.5,
	"itemprice_2": 34.99,
	"quantityonhand": 859,
	"imagefilename": "https://www.cosmostylejewelry.com/CosmoImg/C180960209.JPG, https://www.cosmostylejewelry.com/CosmoImg/C180960209-2.JPG, https://www.cosmostylejewelry.com/CosmoImg/C180960209-3.JPG, https://www.cosmostylejewelry.com/CosmoImg/C180960209-4.JPG, https://www.cosmostylejewelry.com/CosmoImg/C180960209-5.JPG"
}, {
	"vItemNumber": "C183490026",
	"vLocation": "400",
	"vDescription": "",
	"vShortDesc": "20pc Felt Insert Refill",
	"vLook": "Zen",
	"vGenColor": "Grey",
	"vGenMaterial": "Felt",
	"vGenItemType": "Accessories",
	"vMetalColor": "",
	"vSizeType": null,
	"vMetalType": "",
	"vKeywords": "Essential oil",
	"vOnSale": "N",
	"vFeaturedItem": "N",
	"vSorting": 480,
	"vAggregation": null,
	"vMaterialDesc": "100% felt",
	"vFeatureDesc": "20pc felt strips for diffuser refills",
	"vDetailDesc": "Apply several drops of essential oil to felt strip and insert in your tube diffuser for a scent that lasts all day",
	"itemprice_1": 3,
	"itemprice_2": 0,
	"quantityonhand": 466,
	"imagefilename": "https://www.cosmostylejewelry.com/CosmoImg/C183490026.JPG, https://www.cosmostylejewelry.com/CosmoImg/C183490026-2.JPG, https://www.cosmostylejewelry.com/CosmoImg/C183490026-3.JPG, https://www.cosmostylejewelry.com/CosmoImg/C183490026-4.JPG, https://www.cosmostylejewelry.com/CosmoImg/C183490026-5.JPG"
}]